### ISSUE TITLE
Alpha and hue values can exceed expected values when using sliders

### ISSUE THREAD

**Issue by andymcwraith** [Wondermarin/react-color-palette#23]
### My Environment

| Dependency                  | Version  |
| --------------------------- | -------- |
| Node.JS version             | 12.4.0   |
| react-color-palette version | v6.1.0   |

### Expected Behavior:

When using the 'alpha' and 'hue' sliders I expect the hue value to not exceed 360° and the alpha value to not exceed 1.

### Actual Behavior:

Hue and alpha values exceed 360° and 1 (respectively), easily reproducible [here](https://codesandbox.io/s/objective-sun-5z329) (try sliding either slider all the way to the right).

**Comment by RickvdStaaij** [comment]
Experiencing the same with the alpha slider, demo (v6.1.0):

![color-opacity-over-100](https://user-images.githubusercontent.com/6495166/140490258-42530041-b8b8-4093-b337-09929750e0bb.gif)

**Comment by RickvdStaaij** [comment]
@Wondermarin thank you for the fix and the merge :+1: Can you release version 6.1.1 please? Would love to have this fixed in my project too :ok_hand:

**Comment by Wondermarin** [comment]
> @Wondermarin thank you for the fix and the merge 👍 Can you release version 6.1.1 please? Would love to have this fixed in my project too 👌

The next version will be released this week!

**Comment by Wondermarin** [comment]
Fixed in [v6.2.0](https://github.com/Wondermarin/react-color-palette/releases/tag/v6.2.0)!

**Comment by RickvdStaaij** [comment]
@Wondermarin I just updated to the latest version, but I'm afraid it isn't fixed yet. The behavior is still the same as I posted before:

> ![](https://user-images.githubusercontent.com/6495166/140490258-42530041-b8b8-4093-b337-09929750e0bb.gif)

I double checked that I updated to the latest version:
`yarn.lock`:
```
react-color-palette@^6.2.0:
  version "6.2.0"
  resolved "https://registry.yarnpkg.com/react-color-palette/-/react-color-palette-6.2.0.tgz#aa3be88f6953d57502c00f4433692129ffbad3e7"
  integrity sha512-9rIboaRJNoeF8aCI2f3J8wgMyhl74SnGmZLDjor3bKf0iDBhP2EBv0/jGmm0hrj6OackGCqtWl5ZvM89XUc3sg==
```
Plus I made sure I removed all my nextjs cache, and the problem still exists.

**Comment by Wondermarin** [comment]
> @Wondermarin I just updated to the latest version, but I'm afraid it isn't fixed yet. The behavior is still the same as I posted before:
> 
> > ![](https://user-images.githubusercontent.com/6495166/140490258-42530041-b8b8-4093-b337-09929750e0bb.gif)
> 
> I double checked that I updated to the latest version: `yarn.lock`:
> 
> ```
> react-color-palette@^6.2.0:
>   version "6.2.0"
>   resolved "https://registry.yarnpkg.com/react-color-palette/-/react-color-palette-6.2.0.tgz#aa3be88f6953d57502c00f4433692129ffbad3e7"
>   integrity sha512-9rIboaRJNoeF8aCI2f3J8wgMyhl74SnGmZLDjor3bKf0iDBhP2EBv0/jGmm0hrj6OackGCqtWl5ZvM89XUc3sg==
> ```
> 
> Plus I made sure I removed all my nextjs cache, and the problem still exists.

Can you attach a link to codesandbox?
