### ISSUE TITLE
Color picker doesn't support being moved or resized

### ISSUE THREAD

**Issue by msebire** [Wondermarin/react-color-palette#58]
### My Environment

| Dependency                  | Version  |
| --------------------------- | -------- |
| Node.JS version             | v20.5.0   |
| react-color-palette version | v7.0.2   |

### Expected Behavior:

I can move/resize the component that contains the ColorPicker without any issues.

### Actual Behavior:

When moving/resizing the element that contains the ColorPicker, the Saturation component boundaries stay the one from the first render ( the zone where the mouse can move the cursor is offset from the actual display zone ).

### Additional Context:

From my investigation, the issue is related to the Interactive component & the useBoundingClientRect hook.
As the useBoundingClientRect does the node#getBoundingClientRect only during the first render, any changes (either position or size) are not taken into account.

To deal with position changes, the move event handler from the Interactive component should get an updated left & top position in order to be accurate.

**Comment by Wondermarin** [comment]
@msebire, should be fixed in v7.0.3

**Comment by msebire** [comment]
Thanks.
I can confirm 7.0.3 fix the resize issue.

Unfortunately, the move issue is still there.
If you want a simple repro case to see it, you need to put the ColorPicker in a scrollable container and scroll it.
The color dot is then not aligned with the mouse, if you scroll to the initial position, they are back in sync.

**Comment by Wondermarin** [comment]
Could you open a new issue with an example on codesandbox? I'll take a look tomorrow and fix it.
